import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { FilePicker } from "./components/FilePicker.slint";
import { VersionPicker } from "./components/VersionPicker.slint";

export component AppWindow inherits Window {
    title: "TIA Portal Automation Tool by Titus Global Tech";

    callback request-increase-value();
    callback select-json();

    in-out property<int> counter: 42;

    VerticalBox { 
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => { 
                root.request-increase-value();
            }
        }
        HorizontalBox {
            FilePicker {
              button_text: "Import .json config";
              selected_file: "Empty";
              select_file => {root.select_json()} 
            }
            FilePicker {
              button_text: "Open Library";
              selected_file: "None";
            }
            VersionPicker {}
        }
     }
}
