import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { FilePicker } from "./components/FilePicker.slint";

export component AppWindow inherits Window {
    in-out property<int> counter: 42;
    callback request-increase-value();
    VerticalBox { 
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => { 
                root.request-increase-value();
            }
        }
        HorizontalBox {
            FilePicker {
              button_text: "Import .json config";
              selected_file: "Empty";
            }
            FilePicker {
              button_text: "Open Library";
              selected_file: "None";
            }
        }
     }
}
